# Generated by Django 5.0.6 on 2024-06-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=60)),
                ('isbn', models.CharField(max_length=13)),
                ('genero', models.CharField(max_length=10)),
                ('numero_disponible', models.IntegerField(max_length=3)),
                ('numero_ocupado', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('correo', models.CharField(max_length=150)),
                ('tipoUsuario', models.IntegerField(choices=[(1, 'Lector'), (2, 'Bibliotecario'), (3, 'Administrador')])),
            ],
        ),
    ]
