# Generated by Django 5.0.6 on 2024-06-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='numero_disponible',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='numero_ocupado',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('estado_prestamo', models.IntegerField(choices=[(1, 'Préstamo'), (2, 'Entregado'), (3, 'Cancelado')])),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo', to='libreria.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo', to='libreria.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_multa', models.IntegerField()),
                ('usuario_multado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multa', to='libreria.usuario')),
                ('pretamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multa', to='libreria.prestamo')),
            ],
        ),
    ]
