# Generated by Django 5.0.6 on 2024-06-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_alter_libro_genero_alter_libro_numero_disponible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multa',
            old_name='pretamo',
            new_name='prestamo',
        ),
    ]
