# Generated by Django 5.0.6 on 2024-06-25 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_multa_fecha_multa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='estado_multa',
            field=models.IntegerField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default=1),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado_prestamo',
            field=models.IntegerField(choices=[('Préstamo', 'Préstamo'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default=1),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamo', to='libreria.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.IntegerField(choices=[('Lector', 'Lector'), ('Bibliotecario', 'Bibliotecario'), ('Administrador', 'Administrador')], default=1),
        ),
    ]
