# Generated by Django 5.0.6 on 2024-06-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_alter_multa_estado_multa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='estado_multa',
            field=models.IntegerField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado_prestamo',
            field=models.IntegerField(choices=[('Préstamo', 'Préstamo'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.IntegerField(choices=[('Lector', 'Lector'), ('Bibliotecario', 'Bibliotecario'), ('Administrador', 'Administrador')]),
        ),
    ]
