# Generated by Django 5.0.6 on 2024-06-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_alter_multa_estado_multa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='estado_multa',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], max_length=60),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado_prestamo',
            field=models.CharField(choices=[('Préstamo', 'Préstamo'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[('Lector', 'Lector'), ('Bibliotecario', 'Bibliotecario'), ('Administrador', 'Administrador')], max_length=60),
        ),
    ]
